### ISSUE TITLE
Re-theming

### ISSUE THREAD

**Issue by JacksonBates** [JacksonBates/blog#1]
## Note to Hacktoberfest participants

Wait until Oct 1 to open your PR as this will make sure it is counted for Hacktoberfest.

## Change

Implement this theme: http://jekyllthemes.org/themes/jekyll-theme-chirpy/

And modify any existing page elements / structure required to make it work.

**Comment by virtual** [comment]
Could I please look into working on this? @JacksonBates

**Comment by JacksonBates** [comment]
Assigned :)

Happy hacking and good luck with Hacktoberfest.

**Comment by virtual** [comment]
I apparently don't know how to link the PR correctly, but please see PR #3
