### ISSUE TITLE
Correct the code snippet on canonical-url blog post

### ISSUE THREAD

**Issue by JacksonBates** [JacksonBates/blog#2]
## Note to Hacktoberfest participants

Do not open your pull request before 1st October 2020, or it will not count towards your 4 PRs for Hacktoberfest.

## Overview

On https://blog.jacksonbates.com/canonical-url the code snippet should be updated to reflect the new url.

## File

https://github.com/JacksonBates/blog/blob/master/_posts/2019-06-14-setting-canonical-urls-with-poole-jekyll.md

## Change
```html
<link
  rel="canonical"
  href="https://jacksonbates.github.io/blog/canonical-url"
/>
```

should be:

```html
<link
  rel="canonical"
  href="https://blog.jacksonbates.com/canonical-url"
/>
```

**Comment by virtual** [comment]
Should it be this instead, referencing the `page.url` variable?

```html
<link 
  rel="canonical" 
  href="https://blog.jacksonbates.com{{ page.url }}" 
/>
```

**Comment by JacksonBates** [comment]
Haha, yes - I just copy pasted it and forgot to update it!

**Comment by virtual** [comment]
Can I do this PR if no one else is jumping on it? :)

**Comment by JacksonBates** [comment]
Yep, go for it @virtual
